apiVersion: v1
kind: Service
metadata:
  name: nm-pyt-api
spec:
  type: ClusterIP
  selector:
    app: nm-pyt-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-pyt-api-deployment
  labels:
    app: nm-pyt-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nm-pyt-api
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nm-pyt-api
    spec:
      containers:
      - name: nm-pyt-api-container
        image: eu.gcr.io/lbg-mea-14/nm-pyt-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080